
- name: Get list users (JSON)
  ansible.builtin.command: "pveum user list --output-format json"
  register: cmd_users

- name: Get list roles (JSON)
  ansible.builtin.command: "pveum role list --output-format json"
  register: cmd_roles

- name: Load Users
  ansible.builtin.set_fact:
    registered_users: "{{ cmd_users.stdout | from_json | community.general.groupby_as_dict('userid') }}"
    registered_roles: "{{ cmd_roles.stdout | from_json | community.general.groupby_as_dict('roleid') }}"
