- hosts: all
  become: false
  gather_facts: false

  tasks:

    - name: Configure repository
      include_role:
        name: pre-configure-pve

    - name: Pre load Users and Roles
      include_role:
        name: pre-load-pve

    - name: Configure storages
      include_role:
        name: pre-configure-storages
      with_items: '{{ storages }}'
      loop_control:
        loop_var: storage

    - name: Configure roles
      include_role:
        name: pre-configure-roles
      with_items: '{{ roles }}'
      loop_control:
        loop_var: role
      when: registered_roles is not search(role.name)

    - name: Configure users
      include_role:
        name: pre-configure-users
      with_items: '{{ users }}'
      loop_control:
        loop_var: user
      when: registered_users is not search(user.api_user)

    - name: Configure sudo users
      include_role:
        name: set-user-sudo
      with_items: '{{ sudo_users }}'
      loop_control:
        loop_var: user
      when: sudo_users is defined
    
- hosts: localhost
  become: false
  gather_facts: false

  tasks:

    - name: Save tokens
      include_role:
        name: persist-tokens
      with_items: "{{ groups['all'] }}"
      vars:
        tokens: "{{ hostvars[item]['tokens'] }}"
