
- name: setup resources variables
  ansible.builtin.assemble:
    src: '{{ project_path }}/resources/proxmox/{{ item }}/'
    dest: '{{ project_path }}/group_vars/proxmox/{{ item }}'
    remote_src: false
  with_items: 
    - roles
    - users
    - storages
    - sudo_users
  delegate_to: proxmox