---
version: "3.2"

volumes:
  homelab-iac:

services:

  homelab-iac:
    image: homelab/iac:v1
    container_name: homelab-iac
    user: 1001:1000
    volumes: 
      - ./proxmox:/opt/ansible/iac
      - homelab-iac:/home/semaphore
    ports:
      - 3000:3000
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@me.com
      SEMAPHORE_ADMIN: admin