
- name: Add DNS to /etc/resolv.conf
  ansible.builtin.lineinfile:
    dest: /etc/resolv.conf
    search_string: 'nameserver {{ dns_ip }}'
    insertbefore: '^nameserver'
    line: 'nameserver {{ dns_ip }}'
  become: yes

- name: Start NFS task
  ansible.builtin.import_tasks: nfs.yml

- name: Start SAMBA task
  ansible.builtin.import_tasks: smb.yml

- name: Start USB task
  ansible.builtin.import_tasks: usb.yml

- name: Set ACL User
  ansible.builtin.import_tasks: acl.yml