
- name: Install NFS dependencias
  ansible.builtin.apt:
    pkg:
    - nfs-kernel-server
    state: latest
    update_cache: yes
  become: yes

- name: Create a NFS path
  ansible.builtin.file:
    path: "{{ nfs_path }}"
    state: directory
  become: yes

- name: Backup file exports
  ansible.builtin.copy:
    src: '/etc/exports'
    dest: '/etc/exports.orig'
    force: no
    remote_src: yes
  become: yes

- name: Configure NFS folders to export
  ansible.builtin.template:
    src: "exports.j2"
    dest: /etc/exports
  become: yes
  notify:
    - restart nsf-server

- name: Set to only use NFS v4 and single port (2049,111)
  ansible.builtin.import_tasks: nfs-v4-restricted.yml

- name: Allow from 192.168.1.0/24 app nfs
  community.general.ufw:
    rule: allow
    src: 192.168.1.0/24
    app: 'nfs'
  become: yes