######################################## HOW TO USE
# - name: Set timezone
#   include_role:
#     name: configure
#     tasks_from: debian/timezone
#   vars:
#     timezone: 'Europe/Dublin'
############################################### END

- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"

- name: restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
  become: yes
