
- name: Convert VMs templates
  community.general.proxmox_kvm:
    api_host: '{{ node_host }}'
    api_user: '{{ api_user }}'
    api_token_id: '{{ api_token_id }}'
    api_token_secret: "{{ lookup('ansible.builtin.file', api_token_secret) }}"
    node: '{{ vm.node }}'
    name: '{{ vm.name }}'
    vmid: '{{ vm.vmid }}'
    state: 'template'
    timeout: 60
  with_items: '{{ machines }}'
  loop_control:
    loop_var: vm
  when: 'vm.state == "template"'