---
- hosts: localhost
  become: false
  gather_facts: false
  
  tasks:

    - name: Create inventory {{ type }}
      template:
        src: templates/inventory.j2
        dest: '../ansible/inventory/{{ type }}.ini'

    - name: Create proxmox host_vars {{ proxmox.alias }}
      template:
        src: templates/host_proxmox.j2
        dest: '../ansible/host_vars/{{ proxmox.alias }}.yml'

    - name: Create node host_vars {{ node.alias }}
      template:
        src: templates/host_node.j2
        dest: '../ansible/host_vars/{{ node.alias }}.yml'

    - name: Create group_vars/all
      template:
        src: templates/group_all.j2
        dest: '../ansible/group_vars/all/vault.yml'

    - name: Create semaphore.json
      template:
        src: templates/semaphore.j2
        dest: '../ansible/semaphore.json'
