id: ubuntu_image_template
namespace: home.lab.cloud

variables:
  path_from: /var/lib/vz/template/iso/
  suffix_name: -server-cloudimg-amd64.img

inputs:

  - id: filename
    type: STRING
    description: "Filname to create"
    required: true
    defaults:
      - ubuntu-template.img

  - id: server
    type: ENUM
    description: "Download servers from https://cloud-images.ubuntu.com"
    required: true
    values:
      - trusty
      - xenial
      - bionic
      - focal
      - jammy
      - mantic
      - noble

  - id: command
    type: STRING
    description: "Commands"
    defaults:
      - --install qemu-guest-agent --run-command "useradd -m -s /bin/bash ubuntu" --root-password password:root

tasks:

  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Download servidor {{ inputs.server }}

  - id: setup
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:

      - id: local_files
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          kestra.ini: |
            [pve]
            {{ secret('PVE_HOST') }} ansible_user={{ secret('PVE_USER') }} ansible_password={{ secret('PVE_PASS') }}
          kestrabook.yml: |
            ---            
            - hosts: pve
              tasks:
                    
                - name: Ensure requirements in place
                  ansible.builtin.apt:
                    pkg:
                    - guestfs-tools
                    - python3-libvirt
                    state: latest
                    update_cache: true
                  become: true

                - name: Copy base image to libvirt directory
                  ansible.builtin.copy:
                    src: "{{ vars.path_from }}{{ inputs.server }}{{ vars.suffix_name }}"
                    dest: "/tmp/{{ inputs.server }}{{ vars.suffix_name }}"
                    force: no
                    remote_src: yes
                  register: copy_results
                  
                - name: Configure the image
                  command: |
                    virt-customize -a /tmp/{{ inputs.server }}{{ vars.suffix_name }}  {{ inputs.command }}
                  when: copy_results is changed
                  
                - name: Copy image configurade to local-lvm
                  ansible.builtin.copy:
                    src: "/tmp/{{ inputs.server }}{{ vars.suffix_name }}"
                    dest: "{{ vars.path_from }}{{ inputs.filename }}"
                    force: no
                    remote_src: yes
                  when: copy_results is changed

      - id: ansible_task
        type: io.kestra.plugin.ansible.cli.AnsibleCLI
        docker:
          image: cytopia/ansible:latest-tools
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        commands:
          - apk add --update sshpass
          - ansible-playbook -i kestra.ini kestrabook.yml