
- name: Create download folder
  ansible.builtin.file:
    path: '{{ storage_path }}'
    state: directory
  become: yes

- name: Download server images
  ansible.builtin.get_url:
    url: '{{ image.url }}'
    dest: '{{ storage_path }}/{{ image.os_file }}'
    checksum: '{{ image.checksum }}'
  with_items: '{{ os_images }}'
  loop_control:
    loop_var: image
  when: 'image.state == "present"'
  become: yes
