---
version: "3.2"

services:

  homelab-pas:
    image: homelab/pas:v1
    container_name: homelab-pas
    user: 1001:1000
    volumes: 
      - ./ansible:/opt/ansible/pas
      - ./terraform:/opt/terraform/pas
    ports:
      - 3001:3000
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@me.com
      SEMAPHORE_ADMIN: admin