---
- hosts: node
  become: false
  gather_facts: false

  tasks:

    - name: Download servers
      include_role:
        name: node
        tasks_from: download_servers
      vars:
        storage_path: '{{ storage.images.path }}/0'
      tags:
        - node

    - name: Build cloud-init files
      include_role:
        name: node
        tasks_from: create_cloud_init_files
      vars:
        storage_path: '{{ storage.snippets.path }}'
      tags:
        - node


- hosts: node[0]
  become: false
  gather_facts: false

  tasks:

    - name: Create virtual machines
      include_role:
        name: node
        tasks_from: create_vms
      vars:
        node_host: '{{ ansible_host }}'
      tags:
        - node
        - first

    - name: Create template machines
      include_role:
        name: node
        tasks_from: create_templates
      vars:
        node_host: '{{ ansible_host }}'
      tags:
        - node
        - first
