---
- hosts: proxmox
  become: false
  gather_facts: false

  vars:
    public_key_path: "{{ IAC_MODULE }}/security/public-keys"

  tasks:

    - name: Update proxmox rep and pkg
      include_role:
        name: proxmox
        tasks_from: update
      tags:
        - proxmox

    - name: Pre load Users and Roles
      include_role:
        name: proxmox
        tasks_from: pre-tasks
      tags:
        - proxmox

    - name: Update storages
      include_role:
        name: proxmox
        tasks_from: update-storages
      with_items: '{{ storages }}'
      loop_control:
        loop_var: storage
      tags:
        - proxmox

    - name: Update roles
      include_role:
        name: proxmox
        tasks_from: update-roles
      with_items: '{{ roles }}'
      loop_control:
        loop_var: role
      when: registered_roles is not search(role.name)
      tags:
        - proxmox

    - name: Update users
      include_role:
        name: proxmox
        tasks_from: update-users
      with_items: '{{ users }}'
      loop_control:
        loop_var: user
      when: registered_users is not search(user.api_user)
      tags:
        - proxmox

    - name: Sudo privilege for users
      include_role:
        name: proxmox
        tasks_from: set-user-sudo
      with_items: '{{ sudo_users }}'
      loop_control:
        loop_var: user
      when: sudo_users is defined
      tags:
        - proxmox
    
- hosts: localhost
  become: false
  gather_facts: false

  vars:
    token_path: "{{ IAC_MODULE }}/security/tokens"

  tasks:

    - name: Persist file tokens
      include_role:
        name: proxmox
        tasks_from: export-tokens
      with_items: "{{ groups['all'] }}"
      vars:
        tokens: "{{ hostvars[item]['tokens'] }}"
      tags:
        - proxmox
