---
version: "3.2"

volumes:
  homelab:

services:

  homelab:
    build:
      context: .
      dockerfile: config/Dockerfile
    image: homelab:v1
    container_name: homelab
    user: 1001:1000
    volumes: 
      - homelab:/home/semaphore
      - ./IaC/proxmox:/opt/ansible/iac
      - ./PaS/ansible:/opt/ansible/pas
      - ./PaS/terraform:/opt/terraform/pas
    ports:
      - 3000:3000
    env_file:
      - .env

  homelab-iac:
    build:
      context: .
      dockerfile: config/IaC.Dockerfile
    image: homelab/iac:v1

  homelab-pas:
    build:
      context: .
      dockerfile: config/PaS.Dockerfile
    image: homelab/pas:v1
