---
version: "3"

volumes:
  homelab:

services:

  homelab:
    build:
      context: .
    image: homelab/main:v1
    container_name: homelab
    volumes: 
      - homelab:/opt/ansible/files:rw
    ports:
      - 3000:3000
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@me.com
      SEMAPHORE_ADMIN: admin
