---    
- hosts: localhost
  become: false
  gather_facts: false

  vars:
    common:
      target_group_vars:
        - node
      resource_vars:
        - os_images
        - machines
    proxmox:
      resource_vars:
        - roles
        - users
        - storages
        - sudo_users
    node:
      resource_vars: {}

  tasks:

    - name: Build resources variables (common)
      include_role:
        name: common
        tasks_from: build_resources
      vars:
        resource_name: '{{ name }}'
        targets: '{{ common.target_group_vars }}'
      with_items: '{{ common.resource_vars }}'
      loop_control:
        loop_var: name
      tags:
        - resources
        - variables
        - common

    - name: Build resources variables (proxmox)
      include_role:
        name: common
        tasks_from: build_resources
      vars:
        resource_from: '/proxmox'
        resource_name: '{{ name }}'
        targets: 'proxmox'
      with_items: '{{ proxmox.resource_vars }}'
      loop_control:
        loop_var: name
      tags:
        - resources
        - variables
        - proxmox

    - name: Build resources variables (node)
      include_role:
        name: common
        tasks_from: build_resources
      vars:
        resource_from: '/node'
        resource_name: '{{ name }}'
        targets: 'node'
      with_items: '{{ node.resource_vars }}'
      loop_control:
        loop_var: name
      tags:
        - resources
        - variables
        - node

